### ISSUE TITLE
Mixing into if statements

### ISSUE THREAD

**Issue by cookiedragon234** [SpongePowered/Mixin#365] opened 2019-10-01 08:06 UTC
I am trying to modify the result of the if statement on line 410 of GuiInGame. 

For reference, the code is this:
```Java
if (gamesettings.showDebugInfo && !gamesettings.hideGUI && !this.mc.player.hasReducedDebug() && !gamesettings.reducedDebugInfo)
{
	GlStateManager.pushMatrix();
	GlStateManager.translate((float)(l / 2), (float)(i1 / 2), this.zLevel);
	Entity entity = this.mc.getRenderViewEntity();
	GlStateManager.rotate(entity.prevRotationPitch + (entity.rotationPitch - entity.prevRotationPitch) * p_184045_1_, -1.0F, 0.0F, 0.0F);
	GlStateManager.rotate(entity.prevRotationYaw + (entity.rotationYaw - entity.prevRotationYaw) * p_184045_1_, 0.0F, 1.0F, 0.0F);
	GlStateManager.scale(-1.0F, -1.0F, -1.0F);
	OpenGlHelper.renderDirections(10);
	GlStateManager.popMatrix();
}
else
{
	GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.ONE_MINUS_DST_COLOR, GlStateManager.DestFactor.ONE_MINUS_SRC_COLOR, GlStateManager.SourceFactor.ONE, GlStateManager.DestFactor.ZERO);
	GlStateManager.enableAlpha();
    ...
```

Ideally, Id like to be able to force the outcome of the if statement to true in certain conditions. I've tried to redirect the if statement like so:
```Java
@Redirect(method = "renderAttackIndicator", at = @At(value = "INVOKE", target = "if"))
private boolean ifStatement(boolean in)
{
	return true;
}
```
however this doesnt seem to be possible. If anyone knows the solution, I'd love to know :)

**Comment by LoganDark** [comment] 2019-10-01 09:02
> value = "INVOKE", target = "if"

...

**Comment by cookiedragon234** [comment] 2019-10-01 09:16
@LoganDark , yeah its probably the wrong way to do it, but you cant get a target reference for an if statement.

**Comment by LoganDark** [comment] 2019-10-01 09:17
I think in this case you would need to redirect all of the conditions individually, I do agree it would be useful to redirect/modify if statements.

**Comment by cookiedragon234** [comment] 2019-10-01 09:19
@LoganDark How can I redirect a field call? To achieve what I need to, I'd probably only need to modify the value of `gamesettings.showDebugInfo`, however I dont think `@Redirect` works for fields.

**Comment by LoganDark** [comment] 2019-10-01 09:20
@cookiedragon234 I believe you can use org.spongepowered.asm.mixin.injection.points.BeforeFieldAccess + ModifyVariable

**Comment by cookiedragon234** [comment] 2019-10-01 09:21
Thank you, I will try that

**Comment by LoganDark** [comment] 2019-10-01 09:26
I looked into the javadoc and it doesn't seem like ModifyVariable works on anything but the LVT (local variable table?). I don't see any way to modify field accesses so I think this is indeed a missing feature

**Comment by cookiedragon234** [comment] 2019-10-01 09:32
Oh ok, thats annoying. I was previously using an overwrite to achieve that functionality but was trying to move away from it because it caused a crash when running outside of the IDE: https://pastebin.com/f4q9LDde. Do you know what might have caused the crash?

**Comment by LoganDark** [comment] 2019-10-01 09:34
Dude, turn your priority down, your priority 1000 mixin can't modify your priority 999999999 (why?) mixin.

**Comment by cookiedragon234** [comment] 2019-10-01 09:35
oops lol, that could be why. Do we need all of our mixins to have the same priority then?

**Comment by LoganDark** [comment] 2019-10-01 09:36
No, you just need to not overwrite a method and write mixins for it at the same time, because the overwrite will either cause an error when you try to inject into it, or not get applied because it has a lower priority than the injection.

**Comment by cookiedragon234** [comment] 2019-10-01 09:37
Ok, Ill try, thanks :)

**Comment by LoganDark** [comment] 2019-10-01 09:38
Also, I don't think GitHub issues are for this, my Discord is Cuteness#4357.

**Comment by cookiedragon234** [comment] 2019-10-01 09:40
Ok, thanks. Just thought it would be helpful for anyone else with the same issue in the future to have it documented here.

**Comment by Mumfrey** [comment] 2019-10-01 10:22
@LoganDark is correct. For support please use `#mixin` on the sponge discord. Closing as off topic.

**Comment by LoganDark** [comment] 2019-10-01 10:23
@Mumfrey I feel like this is a valid issue as I can't find any way to redirect if statements like that. I just didn't want to have an off-topic discussion in the issue thread.

**Comment by cookiedragon234** [comment] 2019-10-01 11:11
Yep, mixins for basic java statements such as if, switch, else, while, and for would be a great improvement, both with redirecting and other mixin types such as modifying args.

**Comment by LoganDark** [comment] 2019-10-01 12:45
> if, switch, else, while, and for

Okay, that's a little ambitious.

This issue is for JUST if statements. That can be done fairly easily, AFAIK.

Don't go changing things and asking for *all* control statements.

**Comment by cookiedragon234** [comment] 2019-10-01 12:54
Sorry, just trying to give feedback.

**Comment by Mumfrey** [comment] 2019-10-08 11:09
> *@LoganDark said* @Mumfrey I feel like this is a valid issue as I can't find any way to redirect if statements like that. I just didn't want to have an off-topic discussion in the issue thread.

> @cookiedragon234 said* Yep, mixins for basic java statements such as if, switch, else, while, and for would be a great improvement, both with redirecting and other mixin types such as modifying args. Perhaps even mixins for operators such as arithmetic operators.

> *@LoganDark said* This issue is for JUST if statements. That can be done fairly easily, AFAIK.

I'm sorry but it really just isn't simple. Whilst it's true that an `if` gets eventually compiled to a single `JUMP` (of some kind) eventually, actually taking an `if` clause as Java and identifying which jump instruction represents it is nontrivial.

This is largely because Java compiles all kinds of things down to combinations of jump statements including:

* `if` statements (no surprise)
* loops
* logical evaluation

this means that a "simple" `if` block like this one:

```java
if (something && (somethingElse || someOtherThing)) {
    System.err.println("SUCCESS");
}
System.err.println("AFTER");
```
is compiled to no fewer than *three* jump instructions:
```php
    LOAD something
    IFEQ #AFTER
    LOAD somethingElse
    IFNE #BODY
    LOAD someOtherThing
    IFEQ #AFTER
#BODY
FRAME SAME
    INVOKEVIRTUAL System.err.println("SUCCESS")
#AFTER
FRAME SAME
    INVOKEVIRTUAL System.err.println("AFTER")
```
Note that the *first* `IFEQ` is providing the short-circuit *and* behaviour, and jumps over the block if the check fails. The `IFNE` handles the short-circuit *or* behaviour and jumps to the body if the check passes. The final `IFEQ` jumps over the body if the final check fails. It's also important to note that every *target* label which can be "jumped to" must be followed by a stack map frame.

This is easy for a human to decode into logic and then trivial reverse to get something close to the original clause, for a computer it is extremely hard. Analytical decompilers have insanely complicated logic for doing so.

Obviously this means that if you want to target a jump, you need to identify it yourself. This works okay in theory, especially for simple methods, except for the fact that identifying the "correct" jump can be quite difficult in practice. Partly because tracking down the right jump can be a pain to the inexperienced, but also because method structures in terms of jumps can be very fragile and it's not unusual for structure to be different between development and production. This is because decompilation and recompilation inevitably causes minor changes to how logic is compiled. Hell, different versions of `javac` can output different opcodes for the same source code so "it works on my machine" isn't a useful metric either.

Four years ago I was working a feature called *rerouters* which were designed to do exactly this. Taking the abstract structure of jumps in a method and allowing specific ones to be targetted and their logic redirected to a handler. The first stage of this process was visualising jumps in a method:

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_02-04-43.png)

though as you can see the existence of loops clutters things up a bit. With any "jump back" removed from the picture it looked a little cleaner:

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_02-01-30.png)

This was a useful abstraction because to a sufficiently experienced reader, the logic of the method could be matched up to this abstract representation (the number in parens is the opcode index, the number following is the source code line number).

Where this starts to get tricky is with more complex methods:

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_02-05-57.png)

though again this can be significantly simplified by ignoring loops and gotos:

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_02-10-30.png)

The problem of course is still the brittle nature of the jump structure. I hoped to address this by generating a "fingerprint" of the method which could be validated before a rerouter was applied. The fingerprint basically encoded the jump structure of the method as a kind of hash which would need to be included in the rerouter declaration in order for it to be valid. Since even a tiny change in the jump logic of a method can have massive effects, I felt this was the only sensible way to validate that our injection point was sound.

Each instruction also was assigned a unique code which allowed it to be selected (also the ascii-art got kind of nicer as I was working on this feature):

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_17-44-21.png)

Simpler methods with just `if` statements were by far the easiest to pull out of these tables, and drawing the control flow as a graph actually helped significantly with identifying targets that might be relatively safe to inject, versus ones which were far too brittle:

![](http://www.eq2.co.uk/pr/rerouter/2015-04-15_18-22-42.png)

Ultimately this feature was deemed too unreliable and brittle to include, despite quite a lot of discussion around it internally (all these screenshots are dredged up from my screenshots folder from 2015 and formed part of the discussion at the time). I'd still like to include something like it at some point, but the fact of the matter is that targetting jumps is just fundamentally tricky unless you're able to validate your assumptions each time.

As you can probably tell, targetting jumps in certain scenarious can be safe even if it takes a few seconds of analysis to identify the correct one. However in others it can blow up quickly in your face and really needs to be handled very delicately. Since I'm not one to include anything half-baked, this feature is basically shelved until some magical bullet comes along which can bring it up to the levels of reliability I demand for Mixin.

**Closed** 2019-10-08 11:16 UTC
Labels: question

**Comment by Mumfrey** [comment] 2019-10-08 11:17
Oops didn't mean to reopen. I'm happy to discuss this further on discord but I wanted to demonstrate that this isn't something I closed flippantly, a lot of work went into trying to make this work in the past and while it works, it doesn't work to my satisfaction. If people have alternative ideas I'll gladly hear them.

**Comment by cookiedragon234** [comment] 2019-10-08 11:19
Thanks for the detailed response, that makes sense, I can see why it wouldn't be worth it to implement.

**Comment by Mumfrey** [comment] 2019-10-08 11:22
Oh I do believe it's worth it, otherwise I wouldn't have spent so long trying to come up with a solution. The problem is that either the approach I was taking isn't viable, or there's something I'm missing which can make the identification work reliably.

**Comment by Appu26J** [comment] 2023-12-22 05:03
hi
