### ISSUE TITLE
Allow retrieving a list of all mixins for a given class

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#302] opened 2019-02-14 17:25 UTC
When debugging a crash, it's often useful to determine what bytecode transformations may have been applied to a class. To help facilitate this, it would be very useful if Mixin exposed a method (e.g. `Mixins.getMixinsForClass`) that returned a list of all mixin classes applied to a given target class.

**Comment by DemonWav** [comment] 2019-02-14 18:56
MCDev can tell you which all Mixins exist for a class in a particular project, so there's that.

**Comment by Mumfrey** [comment] 2019-02-16 12:28
While this is basically a duplicate of #108, I'm inclined to accept it since that issue has been on the backburner for so long that this has more immediate use and can be implemented relatively easily, especially given recent structural changes.

**Closed** 2019-09-16 15:15 UTC
Labels: core, enhancement
