### ISSUE TITLE
Mixin failing in the presence of LiteLoader

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#222] opened 2017-11-08 08:57 UTC
I've got user reports of crashes with this log : 
https://gist.github.com/Ordinastie/785dd81f71e8a70c2c40695dc874f450#file-fml-log-L992
User confirmed that removal of LiteLoader fixes the issue.

Note that I can't replicate the crash myself, it doesn't happen for me.
For info, here is the mixin : 
https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/java/net/malisis/core/asm/mixin/core/MixinChunkCollision.java#L79

**Comment by Mumfrey** [comment] 2017-11-08 12:21
I think I know what happened, it's because of [this fix](https://github.com/SpongePowered/Mixin/commit/164e471dcda327c41f5348e76b1de3fa5313cb39) which was rolled into 0.7.4 with no version bump because I thought it was minor. I think the current liteloader snapshot ships a version of 0.7.4 which is prior to this patch (by 1 day) and that's causing the failure. This is a liteloader issue rather than a mixin issue.

This was actually reported as a LiteLoader issue [here](http://develop.liteloader.com/liteloader/LiteLoader/issues/36) I've just been too busy to look into it since I've been preparing for a major event from which I have now returned.

Really I should have bumped the version to 0.7.5 when I made that fix, and it would then be the more obvious error of saying "you need version x but version y is loaded" which the `minVersion` is designed to handle, but I dropped the ball and thus we get cryptic errors, which is exactly what `minVersion` is supposed to fix!

Sorry about that, I'll push a new liteloader snapshot when I have a chance and that will rectify the issue. I'm closing this as invalid because the issue is actually on liteloader's end, though I of course don't dispute that it's my fault, it's just not a bug I can fix in Mixin.

**Closed by Mumfrey** 2017-11-08 12:21 UTC

**Comment by Ordinastie** [comment] 2017-11-08 12:36
I'll share blame, I should have looked at LiteLoader issues :p

**Comment by Mumfrey** [comment] 2017-11-08 12:39
Not your fault in any way, I should just be more regimental about bumping the minor version when a potentially breaking change is made. I guess we both learned something from this experience :D
