### ISSUE TITLE
Annotation processor does not compile against JDK 1.8

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Mixin#14] opened 2015-02-04 22:00 UTC
The annotation processor fails to compile against JDK 1.8 since [dcd44b9](https://github.com/SpongePowered/Mixin/commit/dcd44b9). FakeElement and FakeType throw compilation errors on the basis that TypeMirror (indirectly implemented by the two classes) now extends AnnotatedConstruct, the methods of which are not currently implemented in Mixin.

**Comment by Mumfrey** [comment] 2015-02-04 22:45
I know, it's not a high priority though, I'll get to make it work on 1.8 when I have time.

**Comment by caseif** [comment] 2015-02-08 21:29
@Mumfrey Is it plausible to implement the JDK 8 methods without @Override annotations so as not to upset older compilers? I understand it's bad form, but it's by far the simplest solution and doesn't seem to carry any adverse side effects.

**Comment by Mumfrey** [comment] 2015-02-09 11:27
> without @Override annotations

Over my dead body.

Closing this because it's essentially a duplicate of #13 and will be fixed at the same time.

**Closed by Mumfrey** 2015-02-09 11:27 UTC
