### ISSUE TITLE
Access reference to outer class in mixins for inner classes

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#30] opened 2015-03-26 22:41 UTC
Right now accessing references to the outer class in mixins for inner classes is really hard because they have different names in decompiled and binary deobfuscated environment at runtime. In decompiled environment these references are called like `this$0` by the Java decompiler, at runtime the deobfuscator will name them normally with the `field_xxxxx` name.

This makes it nearly impossible to use a `@Shadow` field to access this reference because you can always use only one of the names. Is there some other way to access the references to the outer class from mixins for inner classes already?

Here is an example where this is a problem: https://github.com/SpongePowered/Granite/blob/feature/console/src/main/java/org/spongepowered/granite/mixin/server/MixinConsoleHandler.java#L41-L42

**Comment by Mumfrey** [comment] 2015-03-30 15:34
As far as I can tell, this is happening because FG re-compiles the sources which it decompiles and it is these recompiled classes which are used in dev.

In a nutshell:

* The original mojang source has a (non-static) anonymous inner class, when this is compiled the synthetic field `this$0` is added by the compiler, so far, so good
* Mojang obfuscates the class and the synthetic field is renamed to `a`
* MCP decompiles the class and the name gets a searge name of `field_72428_a`
* As part of the decompilation process the inner class is grafted back in to the original parent class and the synthetic field is removed
* When the newly-decompiled (and forge patched) code is then *re*compiled, the compiler re-creates the synthetic field as `this$0`

The issue is that from a purely automated standpoint, no part of the toolchain (including the mixin processor) knows that `field_72428_a` and `this$0` are related, there is no "mapping" between these two fields because the old one is destroyed and a new one created. Thus we can infer that user-supplied information is required to indicate this association. Knowing this, we just need to decide how best to supply this information to the mixin processor. There are several options:

The most flexible but not necessarily the most elegant is to extend the `@Shadow` annotation with an `aliases` field which can provide alternate names for the target member. This is actually how the original LiteLoader version of the transformer worked, with all possible names for a member being supplied in an [**@**__Obfuscated__](https://www.assembla.com/code/liteloader/subversion/nodes/366/LiteLoader/trunk/java/common/com/mumfrey/liteloader/transformers/Obfuscated.java) annotation (because LiteLoader doesn't have the AP to do the work automatically).

Another option (given that in the development environment we **do** know the outer class (which is not known in production)) would be to add an `@Outer` or similar annotation which would indicate that the field is a reference to the outer class. Since this is then known, the transformer could:

1. Search for the field with the shadow name, if this fails it would then
2. Check if the field is annotated with `@Outer`, if it is it would then
3. verify that the field type matched the (known) outer class of the target and could then
4. search for a synthetic field matching the outer class type in the target class and return this field.
5. If a second `@Outer` annotation is then encountered then an error is raised

A third alternative would be an `@Synthetic` annotation which would work pretty much the same way but could also be used for `var$` synthetic fields.

Personally I'm inclined to go with the first option since it's expressive, concise, puts little additional burden on the transformer, and also has other potential uses, but I'm open to opinions.

**Comment by Mumfrey** [comment] 2015-04-04 23:06
Should be resolved by 872d922a573bb14824ec361d459e8efbb3204191

**Closed by Mumfrey** 2015-04-04 23:06 UTC
Labels: accepted, enhancement
