### ISSUE TITLE
Unable to mix into forge mod in production environment

### ISSUE THREAD

**Issue by GlassSpirit** [SpongePowered/Mixin#308] opened 2019-03-08 17:15 UTC
I am trying to mix into forge mod.
In dev environment everything is fine, but on production mixin system fails to locate targeted classes.
Any suggestions how to do this right?

Here is part of [log from debug.log](https://gist.github.com/gabizou/980ad4b48c5de3cf60a6048547b24e6b)

Also when I place my compiled mixins inside the jar of mod I am hooking in and merge manifests, it works fine

gabizou edit: Use https://gist.github.com/ instead of just pasting logs directly in comments. wrapping makes logs illegible.

**Comment by Mumfrey** [comment] 2019-03-21 12:27
Because of the way classloaders are structured in forge this is not supported because mod classes are not available early enough in startup. It was the intention of #78 to provide better support around this but the functionality has not been high enough priority to devlop further.

I'll consider this a duplicate of #78 since it will be addressed by the completion of that issue. Once the current upgrades are complete I will be looking at older issues to triage anyway.

**Closed by Mumfrey** 2019-03-21 12:27 UTC
