### ISSUE TITLE
Mixin apply failed to replace Minecraft class with my own Mixin version.

### ISSUE THREAD

**Issue by kixkid229** [SpongePowered/Mixin#258] opened 2018-05-27 19:12 UTC
In which neither my Keybind calls nor my Render calls are actually taking place inside of forge.
My error report is shown below:
```
11:02:58	game		info	[15:02:58] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:client.MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @ModifyVariable annotation on localvar$displayGuiScreen$zzc000 specifies a target class 'bib', which is not supported

11:02:59	game		info	[15:02:59] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:entity.MixinEntityLivingBase -> net.minecraft.entity.EntityLivingBase: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching bd:Z in net/minecraft/entity/EntityLivingBase for mixins.uzi.json:entity.MixinEntityLivingBase->@Accessor[FIELD_GETTER]::getIsJumping()Z

11:02:59	game		info	[15:02:59] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:block.MixinBlock -> net.minecraft.block.Block: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$in$zzf000 specifies a target class 'aow', which is not supported

11:03:03	game		info	[15:03:03] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:client.key.MixinKeybinding -> net.minecraft.client.settings.KeyBinding: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching i:Z in net/minecraft/client/settings/KeyBinding for mixins.uzi.json:client.key.MixinKeybinding->@Accessor[FIELD_SETTER]::setPressed(Z)V

11:03:15	game		info	[15:03:15] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:renderer.MixinRenderManager -> net.minecraft.client.renderer.entity.RenderManager: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching o:D in net/minecraft/client/renderer/entity/RenderManager for mixins.uzi.json:renderer.MixinRenderManager->@Accessor[FIELD_GETTER]::getRenderPosX()D

11:03:15	game		info	[15:03:15] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:renderer.MixinRender -> net.minecraft.client.renderer.entity.Render: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$renderLivingLabel$zzb000 specifies a target class 'bzg', which is not supported

11:03:16	game		info	[15:03:16] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:renderer.MixinEntityRenderer -> net.minecraft.client.renderer.EntityRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Redirect annotation on redirect$updateCameraAndRender$renderGameOverlay$zza000 specifies a target class 'buq', which is not supported

11:03:16	game		info	[15:03:16] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:screen.MixinGuiMultiplayer -> net.minecraft.client.gui.GuiMultiplayer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$addAltButton$zzg000 specifies a target class 'bnf', which is not supported

11:03:21	game		info	[15:03:21] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:client.multiplayer.MixinPlayerControllerMP -> net.minecraft.client.multiplayer.PlayerControllerMP: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$onPlayerDamageBlock$zzd000 specifies a target class 'bsa', which is not supported

11:03:22	game		info	[15:03:22] [main/WARN] [mixin]: Mixin apply failed mixins.uzi.json:screen.MixinGuiChest -> net.minecraft.client.gui.inventory.GuiChest: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching w:Lnet/minecraft/inventory/IInventory; in net/minecraft/client/gui/inventory/GuiChest for mixins.uzi.json:screen.MixinGuiChest->@Accessor[FIELD_GETTER]::getUpperChestInventory()Lnet/minecraft/inventory/IInventory;
```
Inside of each of these mixins the calls that I am trying to call are shown below:
```
    @Inject(method = "runTickKeyboard", at = @At(value = "INVOKE_ASSIGN", target = "org/lwjgl/input/Keyboard.getEventKeyState()Z", remap = false))
    private void onKeyEvent(CallbackInfo ci) {
        if (currentScreen != null)
            return;

        boolean down = Keyboard.getEventKeyState();
        int key = Keyboard.getEventKey();
        char ch = Keyboard.getEventCharacter();

        if (down) {
            Uzi.INSTANCE.getEventManager().dispatch(new EventKeyPressed(key));
        }
    }
```
and
```
 @Redirect(method = "updateCameraAndRender", at = @At(value = "INVOKE", target = "net/minecraft/client/gui/GuiIngame.renderGameOverlay(F)V"))
    private void updateCameraAndRender$renderGameOverlay(GuiIngame guiIngame, float partialTicks) {
        guiIngame.renderGameOverlay(partialTicks);
        Uzi.INSTANCE.getEventManager().dispatch(new EventRender.WorldToScreen(partialTicks));
    }
```

Would you happen to know why neither event is getting registered with the mixins on compile but is being registered in debug.

**Comment by kixkid229** [comment] 2018-05-28 16:08
Doing this fixed it aswell as refactoring some mapping stuff. Thanks Mumfrey.

**Comment by Mumfrey** [comment] 2018-05-28 21:38
No problem, since this is not a bug I will close this issue.

**Closed by Mumfrey** 2018-05-28 21:38 UTC
