### ISSUE TITLE
CoreMod coexisting with Mixins always gets obfuscated names instead of srg names in production environment

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#123] opened 2016-04-27 21:52 UTC
I am currently in the process of converting my custom ASM transformers to Mixin, and I noticed that when my ASM transformers and Mixin are used at the same time it works in dev environment, but in production environment it always fails because the code expects srg names, but it's given obfuscated (notch) names.

After asking on #spongedev, the first attempt to solve it was adding `@Resource` annotation, which didn't change anything. Second attempt was to register my transformer directly using `Launch.classLoader.registerTransformer` which didn't work eighter.

**Comment by liach** [comment] 2016-04-27 22:40
Give the repo of your code.

**Comment by Mumfrey** [comment] 2016-04-27 22:42
I'll take a look into it. The class names and bytecode are passed through the normal transformer chain in order to ensure this doesn't happen, but I guess it's possible something has changed in FML or some other circumstances are working to prevent it operating as normal.

**Comment by liach** [comment] 2016-04-27 22:47
@Mumfrey Could you add such conversions to MixinGradle?

**Comment by Mumfrey** [comment] 2016-06-23 15:22
@Barteks2x do you have a recent release of your mod I could test with? Now the new platform handling has been merged I'd like to see if it's improved matters at all, and I also now have a better chance of being able to fix it if it does still happen.

**Comment by Barteks2x** [comment] 2016-06-23 15:43
The latest version that had coremod coexisting with mixins was here: https://github.com/Barteks2x/CubicChunks/tree/7bd996c7f4161ff49be2c23ef81633f9b4410fd0 which is a bit old. As far as I know Mixin can be used with older MC versions so it shouldn't be too hard to try using new Mixin with this old version.

**Comment by Mumfrey** [comment] 2016-06-23 15:49
Ah ok, well I'll concoct a test case instead. Basically I think the problem will still currently exist but I have a potential solution now.

**Comment by Mumfrey** [comment] 2017-01-25 12:40
This should basically not be an issue any more, if it is then please let me know and if possible provide code which demonstrates the bug as I'm unable to reproduce in current releases.

**Closed by Mumfrey** 2017-01-25 12:40 UTC
Labels: bug
