### ISSUE TITLE
Can't use any Injection Points except for HEAD when mixin'ing an anonymous class

### ISSUE THREAD

**Issue by EmotionalLove** [SpongePowered/Mixin#298] opened 2019-01-21 04:41 UTC
When trying to mix into `SplashProgress$2#run()`, trying to use any injection point (such as `INVOKE`, `FIELD`, or `NEW`) will simply do nothing, and not execute. No stacktrace or information is logged when this happens, however code executes fine at the `HEAD`.

I'm not sure if i'm just missing something or if there's an actual problem that mixin is having.

```Java
@Mixin(targets = "net.minecraftforge.fml.client.SplashProgress$2", priority = 999)
public abstract class MixinSplashProgressStart {


    @Inject(
            remap = false,
            method = "run()V",
            at = @At(
                    value = "INVOKE",
                    target = "Lnet/minecraftforge/fml/client/SplashProgress$2;glDisable(I)V"
            )
    )
    public void run(CallbackInfo info) {
        System.out.println("Hey! We are attempting to do something in this method! If you see this msg it means this was executed!");
    }
```

**Comment by liach** [comment] 2019-01-21 08:43
hmm, is glDisable from SplashProgress$2? looks like a static import from GL11.

**Comment by Mumfrey** [comment] 2019-01-21 13:21
I have to agree with @liach, this looks like your injection point descriptor is just incorrect. Are you using the **Bytecode Viewer** plugin in your IDE or a `javap` disassembled output to determine the descriptor? Closing as not a bug, if you still believe otherwise please reopen this ticket.

**Closed by Mumfrey** 2019-01-21 13:21 UTC
