### ISSUE TITLE
ModifyConstant throws a cryptic ArrayIndexOutOfBoundsException when a no-argument method that returns the correct type is annotated

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#456] opened 2021-01-03 02:36 UTC
As in title. This line in Injector.checkCoerce does it:
```java
        Type fromType = index < 0 ? this.returnType : this.methodArgs[index];
```

<todo: add stacktrace>

**Comment by Mumfrey** [comment] 2021-01-20 16:30
Duplicate of #411

**Closed by Mumfrey** 2021-01-20 16:30 UTC
