### ISSUE TITLE
Support explicit constructor descriptor when using a @Redirect with NEW 

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#157] opened 2016-12-31 19:31 UTC
Given the following class: https://gist.github.com/Minecrell/a56ab40b48bf6884f0c64080f4fd6b3b

Unlike for regular method or field redirectors, the `target` / `class` argument of a `@Redirect` with the `NEW` targets only the class name of the `NEW` instruction, not the method parameters of the following constructor call.

Because of that, it is impossible to `@Redirect` one of the constructors of the `create` method in the test class above without specifying an explicit `ordinal`.

```java
@Redirect(method = "create", at = @At(value = "NEW", target = "net/minecrell/test/TestClass95"))
private static TestClass95 onCreateTestClass95(String a) {
    return new TestClass95(a);
}
```

The `@Redirect` above will always fail because the method signature will be wrong for one of the constructor calls. Example error message: https://gist.github.com/Minecrell/b8f1eb42a27ac3fe09e0498ae68c52e6. When I change the method parameters the same error occurs but with the previous method signature again.

In this case using the `ordinal` isn't a big problem because there are only two constructor calls, however when you have a lot of constructor calls with the same descriptor you would have to create a separate `@Redirect`s for all of them. It would be helpful if Mixin would support selecting a specific _constructor call_ instead of only the class of the `NEW` instruction.

For example it could take a method descriptor to the constructor similar to an `INVOKE` `@Redirect`: `Lnet/minecrell/test/TestClass95;<init>(Ljava/lang/String;Ljava/lang/String;)V`

I've created this issue because it was something I've realized while writing an inspection to check the method parameters of `@Redirect` injectors in the MinecraftDev IntelliJ plugin so this isn't top priority to fix/add, I don't actually need it somewhere currently.

**Comment by Mumfrey** [comment] 2016-12-31 20:57
`target` isn't actually used for constructor redirectors but I take your point, it should be omitted because the return type of the handler is what is actually used.

Essentially, the fix for this is not specifying the signature - which is pointless since it's already embedded in the handler signature - but just basically allowing the injector to fail on some calls as long as it succeeds on at least one.

**Comment by Minecrell** [comment] 2016-12-31 21:23
@Mumfrey 
It's possible to use either `target` or the `class` argument in `args`, https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/points/BeforeNew.java#L85

I'd personally prefer if it's consistent with the other types of `@Redirect`s so I don't need to have two different kinds of code completion and validation. If you say that it is embedded in the handler signature, wouldn't the same apply for a regular `@Redirect` of a method? I think having the target similar to the `INVOKE` injection point type would make the usage easier (because it is consistent) and more reliable, especially in this case:

Let's say I add a `String` parameter to the `create` method in my example above:

```java
public static TestClass95 create(String interestingString) {
    System.out.println(interestingString)
    if (new Random().nextBoolean()) {
        return new TestClass95("A", "B");
    } else {
        return new TestClass95("A");
    }
}
```

Now I want to capture it as part of the `@Redirect`. I haven't tested it, but it is possible according to the Javadocs:

> Note that like other redirectors, it is possible to capture the target method's arguments by appending them to the handler method's signature.

```java
@Redirect(method = "create", at = @At(value = "NEW", target = "net/minecrell/test/TestClass95"))
private static TestClass95 onCreateTestClass95(String a, String otherString) {
    return new TestClass95(a);
}
```

Do I want to redirect the constructor with two `String` parameters or redirect the one with a single `String` parameter and capture the `interestingString` additionally? Both would match.

**Comment by Mumfrey** [comment] 2017-01-01 14:51
No you misunderstand: `target` and `class` are to be used when using `NEW` as an injection point. For constructor redirectors you are not supposed to include them (note that [in the javadoc](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/Redirect.html) I only mention using `NEW` keyword).

That said, I see what you're saying about possible ambiguity with the overloads, which is a valid scenario. In this instance I think it makes sense to specify qualified descriptors with the signature and return type:

```java
    @At(value = "NEW", target = "(Ljava/lang/String;IIZ)Ltype/being/Targetted;")
```

since specifying "owner" and "name" in this context doesn't make any sense since the owner will be the same as the return type, and there is no name.

**Comment by Minecrell** [comment] 2017-01-01 15:46
@Mumfrey That's interesting, I didn't know you can actually omit `target` and `class` when using `@Redirect` for constructors. There is no example for the annotation in the Javadoc of `@Redirect` so I was assuming you had to specify the `target` similar to a `@Redirect` for a regular method.

If that is the case I suggest that we also correct @ST-DDT's example in https://github.com/SpongePowered/Mixin/issues/137#issuecomment-251784068 since it also has an explicit definition of the target class.

**Comment by ST-DDT** [comment] 2017-01-01 18:54
Thats fine with me. Maybe show both versions just for completeness. I'm just glad someone actually read that comment and if it can be improved I'm happy.
However I'm not sure about the suggested/required changes, thus I would be glad if someone else could do these changes.

**Comment by Mumfrey** [comment] 2017-01-01 19:30
I'm just changing up the whole way `BeforeNew` works tbh. It was designed for *EventInjectionTransformer* back several years ago but EIT injection points are more flexible and the NEW selector never needed to be that smart (bear in mind that with EIT all obfuscation needed to be done by hand, so avoiding obfuscation was a key concern when designing selectors). Mixin doesn't **yet** support the BEFORE/AFTER/NEXT/PREVIOUS/AND/OR/NOT between injection points that EIT does (though it will do at some point in the future) so it's not currently possible to make the same kind of declarations. Making NEW more support more explicit selectors would seem to be a good idea so I'm just gonna roll with that and say that in general you should declare `target` unless you know you can get away without it (eg. in the situation that the signature is suitably unambiguous).

**Closed** 2017-01-02 00:16 UTC
Labels: accepted, core, enhancement
