### ISSUE TITLE
Minecraft Forge coremod injections into a class break mixins for the same class

### ISSUE THREAD

**Issue by thexaero** [SpongePowered/Mixin#554] opened 2022-01-05 14:47 UTC
In case the issue is on Mixin's end:
https://github.com/MinecraftForge/MinecraftForge/issues/8356

**Comment by Mumfrey** [comment] 2022-01-05 18:27
Duplicate of #550 
Yet another duplicate of McModLauncher/modlauncher#74

**Closed by Mumfrey** 2022-01-05 18:27 UTC
