### ISSUE TITLE
Not providing the SRG file in build.gradle results in NPE during compile step

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#5] opened 2015-01-04 23:56 UTC
We discovered today that when gradle downloaded the newest snapshot of Mixin for Almura we could no longer perform a compilation due to missing the SRG or mappings.

Mixin should handle this without bombing on javac step.

**Comment by Mumfrey** [comment] 2015-01-05 00:58
This was actually intentional, but can be changed. Not having mappings is an error condition as far as mixins are concerned. I can make the error message more descriptive than the exception that gets thrown if that woul be better?

**Comment by Mumfrey** [comment] 2015-01-05 02:01
Closing because this is the intended behaviour, the AP does output a compiler error message as well as the NPE stack trace.

**Closed by Mumfrey** 2015-01-05 02:01 UTC

**Comment by Mumfrey** [comment] 2015-01-05 16:44
I've compromised and have it only throw a hissy-fit if it actually hits an annotation which requires remapping. This should allow the error to be suppressed when working with purely non-obfuscated targets by setting ```remap=false``` on all mixin annotations.
