### ISSUE TITLE
Equivalent of @Override/@Overwrite for non-obfuscated methods

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#179] opened 2017-05-19 21:54 UTC
Currently there is no way to do any compiletime checks to make sure the method I'm overwriting exists when it's non obfuscated one/doesn't have mappings.

**Comment by Mumfrey** [comment] 2017-05-22 11:30
I see. Yes this dates back to Mixin behaviour *pre-Mixin* (in the `ClassOverlayTransformer` days when overlays were tightly coupled with their target class and *everything* was meant to overwrite. However today it doesn't really fit in with the way mixins are being used.

Of course there's the *opposite*, with `@Unique`, but no declarative intention to overwrite a non-obfuscated method. I feel like this could be addressed in two ways:

* **Major version bump** accompanied by a paradigm shift were `@Overwrite` is *required* to overwrite a target method. This would have to be a major version bump because it would require editing basically all mixins which currently leverage implicit overwriting.

* **Minor version bump** but add a `remap=false` attribute to `@Overwrite` like other annotations have, allowing it to be used in the case where you wish to *explicitly* check a target method exists before overwriting, facilitating a compile-time check as well.

Not sure which is better, although of course both are possible if I do the minor one first and then change the behaviour wholesale in the future at some point.

**Comment by Barteks2x** [comment] 2017-05-22 11:45
What about just allowing the `@Overwrite` to be there and showing a warning if it's not there, just like what java does with `@Override`? This wouldn't break any existing code, and still allow `@Overwrite` to be used on non-obfuscated methods wighout that extra `remap = false`.

**Comment by Mumfrey** [comment] 2017-05-24 11:42
Whilst it would work, I'm not a fan of surreptitiously changing the behaviour like that. `@Overwrite` currently has a clearly-defined contract and if that contract is changed then it should be obvious to the developer. In the cases outlined above, the new usage would be clearly demarcated.

In your scenario, allowing it to silently succeed for non-obfuscated methods is actually a regression, because it's *currently* expected that it should fail at compile-time if a decorated method is targetting a non-obfuscated method for overwriting. Using a `remap` attribute has the following effects:

* Prevents code relying on the new behaviour compiling on the old version (because `remap` doesn't exist)
* Allows the new behaviour to be processed whilst retaining the old behaviour.

Likewise, changing it wholesale is also ok, because any code currently relying on *implcit* overwrites needs to be updated anyway to make them explcit. However silently changing the behaviour of one of the oldest and most established annotations is not something I would consider.

**Comment by Mumfrey** [comment] 2017-07-05 08:13
This will change in 0.7. I'm still not *requiring* `@Overwrite` since I feel like the "don't overwrite things" is already properly handled with `@Unique`. However I am making the following changes:

* Adding a `remap` argument to the annotation, to allow it to be used for non-obfuscated methods
* Adding a config-level option to only overwrite methods if the annotation is present. This preserves the old behaviour but supports a more deterministic operation for people who wish to use it without breaking backwards compatibility.

**Comment by Mumfrey** [comment] 2017-07-06 14:05
Added in 0.7-dev, commits 41e53c49425c854ff8d44104a18246d9b9e672c0 and 50660894fcfdcd8847b60e39978000f2ac097d31

**Closed by Mumfrey** 2017-07-06 14:05 UTC
Labels: accepted, annotation processor, core, enhancement
