### ISSUE TITLE
Annotation Processor still doesn't work properly in IntelliJ

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#48] opened 2015-05-23 16:08 UTC
After setting up the annotation processor from the latest build of Mixin, I was pleased to find it worked well with Intellij IDEA. However when attempting to compile, my builds were failing at the AP because of `@Inject` mapping failures. 

Some of which were caused by spaces in the target method `@At` others because of MixinToSubClass extends MixinToSuperClass wasn't being recognized properly, expecting MixinToSubClass extends SubClass.

All of these so-called "errors" from the AP during compile, will run and apply just fine during a test run of the server. In fact the code itself is fairly old (MixinLeafBlock in SpongeCommon). I see this as a failure in the provided annotation processor.

**Comment by Mumfrey** [comment] 2015-05-23 17:41
> After setting up the annotation processor from the latest build of Mixin, I was pleased to find it worked well with Intellij IDEA. However when attempting to compile, my builds were failing at the AP because of @Inject mapping failures.

Do not be vague, you need to provide specific examples of failure for me to stand any chance of fixing this. As a developer yourself you should understand that posting the actual error is important.

> Some of which were caused by spaces in the target method @At

That seems unlikely, since they would also fail at build time, and spaces are trimmed anyway.

> others because of MixinToSubClass extends MixinToSuperClass wasn't being recognized properly, expecting MixinToSubClass extends SubClass.

Disable incremental building.

> All of these so-called "errors" from the AP during compile, will run and apply just fine during a test run of the server.

Remember the AP's job. The AP is responsible for checking that Mixins can safely traverse the obfuscation boundary, failing the build when they can't, and providing the necessary information to make it possible when they can. This means that the AP raising an error doesn't mean the server won't run as is, it means that the AP can't do its job and is erroring so that it can be fixed. So you can't say *"so-called errors"* because they are still errors, just errors of a different kind which it is the AP's responsibility to report.

> In fact the code itself is fairly old (MixinLeafBlock in SpongeCommon). I see this as a failure in the provided annotation processor.

Except that the AP works perfectly well in the gradle builds it was designed for, and in Eclipse which supports Annotation Processors properly. I'm not saying I won't fix it for IntelliJ if it's possible, but blaming IntelliJ's failings on the AP (and being so rude about your phrasing in doing so) doesn't really seem appropriate.

Provide some more information about the `@Inject` lines it's flagging as erroneous and I'll look into it. The incremental build thing I can't fix because it's just a function of the fact that the AP needs the whole AST available in order to run the validator, and IntelliJ only provides part of it, which makes the validation fail.

**Comment by modwizcode** [comment] 2015-05-23 17:54
Ok I'll get those error messages posted.

**Comment by Mumfrey** [comment] 2015-05-23 17:56
Ok cool. If it's possible to at least make the AP work *partially* on IntelliJ then it's worth a try. But atfer wasting hours on it in the first place and getting nowhere (with the help of AzureusNation and gabizou as well) I basically just realised that IntelliJ's AP support is horribly broken. If they've improved matters in the newer version then we can have another stab at it.

**Comment by luacs1998** [comment] 2015-05-24 02:44
Well, would also like to chime in that I'm also getting "No obfuscation mapping for @overwrite method" errors, but only in IntelliJ. Building through Gradle works fine.

**Comment by modwizcode** [comment] 2015-05-24 16:00
I haven't seen that error, I found that telling IntelliJ to use the eclipse java compiler instead of javac seemed to partially fix this for me until I did a rebuild. I don't actually have error logs to give I only get the basic warnings from the AP.

**Comment by modwizcode** [comment] 2015-05-24 19:05
I was wrong about the annotations working for the build, the MixinBlockLeaves fails to remap through gradle as well. It's just the incremental build failure, which I'm not sure how that's supposed to be disabled I cannot find an option for it.

**Comment by Mumfrey** [comment] 2015-05-24 23:55
The only thing I can think to fix the incremental build issue is to provide an option to turn it off which sucks because then you don't get the benefit of that check. The other option is just sticking with the current status of IntelliJ just not being supported.

**Closed** 2015-06-04 15:08 UTC
