### ISSUE TITLE
Mixin not reobfuscating non-mc fields

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Mixin#233] opened 2018-01-25 23:11 UTC
I have the following code that modifies a non-mc class (a class from another mod):

```java
@Mixin(value = EntityFlorb.class)
public abstract class MixinEntityFlorb extends EntityThrowable {

    public MixinEntityFlorb(World world) {
        super(world);
    }

    @Inject(method = "onImpact", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;setBlock(IIILnet/minecraft/block/Block;II)Z", shift = At.Shift.BEFORE), cancellable = true)
    private void injectImpact(MovingObjectPosition mop, CallbackInfo ci) {
    // code
    }

}
```

On my IDE, I have the deobfuscated version of the mod that has this class. The target method overrides `onImpact`, which is a minecraft method, from EntityThrowable. The problem is that Mixin is not reobfuscating the `onImpact`, so after compiling, it still `onImpact` instead `func_70184_a`. This works when mixing into minecraft/forge classes, just not on classes that aren't from MC.

**Comment by ryantheleach** [comment] 2018-01-26 14:18
@Eufranio Try reading over Mumfrey's reply here, and see if it helps at all.

https://github.com/SpongePowered/Mixin/issues/133

**Comment by Eufranio** [comment] 2018-01-26 14:23
Hmm, my refmaps are ok and as I said, it is able to reobfuscate vanilla mixins correctly. Unless there's a special setup for using it along with other mods, it might not be causing this problem...

**Comment by Mumfrey** [comment] 2018-01-26 18:19
What happens if you fully-qualify the the method reference instead of just using the name. I don't think the AP is going to have enough information available to reobf the reference with just the name.

**Comment by Eufranio** [comment] 2018-01-27 15:52
Same error, `@Inject annotation on handler$injectImpact$zbe000 could not find 'onImpact'`, using the filly-qualified name:
```java
@Inject(method = "Lcofh/thermalexpansion/entity/projectile/EntityFlorb;onImpact(Lnet/minecraft/util/MovingObjectPosition;)V", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;setBlock(IIILnet/minecraft/block/Block;II)Z"), cancellable = true)
    private void injectImpact(MovingObjectPosition mop, CallbackInfo ci) {
        //code
    }
```

Maybe because `onImpact` is a method of `EntityFlorb.class`, which extends EntityThrowable, and not `EntityThrowable.class`?

**Comment by Mumfrey** [comment] 2018-01-27 17:58
The extends isn't a problem as long as the AST is available for the class at compile time. The annotation processor is able to handle this kind of situation by looking up the superclass information of the target class until it finds an obf mapping for the reference (or not).

Does `EntityFlorb` exist on your compile-time classpath?

**Comment by Eufranio** [comment] 2018-01-27 20:50
Yes, `EntityFlorb` exist on my compile classpath, trough a deobfuscated jar as compile dependency.

**Comment by Mumfrey** [comment] 2018-02-26 12:11
Having investigated this further, I'm still unable to reproduce the issue with a deobf dependency provided via gradle, as fas as I can tell the AP handles this situation exactly as it should and correctly resolves the method name and contributes it to the refmap.

Can you please upload your project or an MCVE reproduction of the problem so I can use it to diagnose the problem.

**Comment by Mumfrey** [comment] 2018-04-18 13:49
Closing for now as no clarification is forthcoming and I cannot reproduce this.

**Closed by Mumfrey** 2018-04-18 13:49 UTC
Labels: clarification needed
