### ISSUE TITLE
Warn when a transformer exclusion is applied to a Mixin class

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#259] opened 2018-06-02 21:26 UTC
As @Barteks2x and I recently discovered, some Forge mods end up accidentally adding a transformer exclusion for their Mixin classes (e.g. by excluding a parent package). This prevents a production jar from being used in a development environment, since the mixin classes will not be debofuscated before being applied.

It can be difficult to trace the problems caused by this (e.g.  a `NoSuchMethodError` from a method added by a mixin) back to the original transformer exclusion. To make it easier for Mixin users to determine when this is occuring, it would be helpful if Mixin were to log a warning whenver it detects that a transformer exclusion applies to a Mixin class.

**Comment by Barteks2x** [comment] 2018-06-02 21:32
Previously I didn't even realize this is caused by transformer exclusion and reported this https://github.com/SpongePowered/Mixin/issues/256

**Comment by Mumfrey** [comment] 2018-06-03 01:07
Nice detective work. This kind of thing should hopefully go away in the long run but fixing it for LegacyLauncher is not a massive ask.

**Comment by Mumfrey** [comment] 2018-06-11 14:34
Closed via 2d410a79df9d4aa4ed1c5004603064849c3eac9a

**Closed by Mumfrey** 2018-06-11 14:34 UTC
Labels: core, enhancement
