### ISSUE TITLE
Incompatibility with forge?

### ISSUE THREAD

**Issue by zeroeightytsix** [SpongePowered/Mixin#205] opened 2017-08-23 14:31 UTC
Hello, I'm trying to use mixins for a 1.12.1 forgemod I'm starting on.
However, my mod will error upon launch due to mixins using guava 17 and forge using guava 21. 
My build.gradle: https://pastebin.com/aCjFs2qZ
Forge 1.12.1-14.22.0.2460
How would I go about fixing this? I'm a total noob at working with gradle and such, please be nice~

edit: Stacktrace: https://pastebin.com/Lud83tgY

**Comment by Mumfrey** [comment] 2017-08-23 14:45
Duplicate of #186, just manually evict the guava dependency in your build script, I see that you're already evicting `launchwrapper` so you already know the syntax to do so.

**Closed by Mumfrey** 2017-08-23 14:45 UTC
