### ISSUE TITLE
IllegalArgumentException when trying to grab locals if classNode.name is null

### ISSUE THREAD

**Issue by Boundarybreaker** [SpongePowered/Mixin#295] opened 2018-12-26 07:50 UTC
[mixin/target/log](https://gist.github.com/Boundarybreaker/de36bdaa732a754420b4fbbdd999a5b4)

[Line 150 of org/spongepowered/asm/util/Locals.java](https://github.com/SpongePowered/Mixin/blob/81a22a4f1d1cf59089bed40cdab4913860340c22/src/main/java/org/spongepowered/asm/util/Locals.java#L150) calls for a classNode's name without making a proper descriptor. This can lead to IllegalArgumentExceptions if the name is null. I ran into this issue while trying to use mixins for a Fabric mod today, and it caused crashes before I could even run a `LocalCapture.PRINT`. There should be a descriptor to prevent this.

**Comment by Mumfrey** [comment] 2018-12-26 16:11
That's pretty unusual, to my knowledge there's no situation where the `name` field of a `ClassNode` should be `null` (hence no null-check). While the general contract of `ClassNode` doesn't stipulate nullability, other parts of ASM's API do do pre-flight checks on the name (eg. ClassVisitor) and throw errors if the class name is null.

Whilst I can fix this so that Mixin doesn't choke on it, I feel like the "fix" is actually to throw an exception anway, since that field being null is an error condition, Mixin is just the first thing *seeing* the error condition. It's almost certainly worth checking where that `null` value came from as there's probably other things which will choke on it, and it's worth tracking down where the error condition originates in the first place. My first guess would be a synthetic class which is being impoperly generated, or a remapping adapter of some sort which is erroneously returning `null` when it shouldn't.

Either way, I'll put the null check in Mixin and have it generate a more sensible crash than an NPE.

All changes are going into 0.8 at this point so this enhancement won't appear in the current 0.7.x release, but will be rolled up into the next.

**Comment by Boundarybreaker** [comment] 2018-12-26 21:33
Yeah, I think having it throw a more understandable crash would be the best thing to do.

**Comment by InsomniaKitten** [comment] 2018-12-30 19:47
This appears to be caused by the fact that Fabric's fork of Mixin has updated ASM dependency to 7.0, and semantics have since changed that break expectations.

**Comment by Runemoro** [comment] 2018-12-30 19:50
ASM7 now throws an exception if the descriptor is invalid:

https://gitlab.ow2.org/asm/asm/commit/6db046e2003c6015c2a4c027db6d0b699b1d5117#ce423ae3db5f0e248402538bf9a7f74db617de5f_412_429

**Comment by DemonWav** [comment] 2019-01-01 19:09
You really can't just upgrade ASM like that willy-nilly without checking anything like that...

Sounds like Fabric should fix it in their fork, it doesn't make sense for Mixin to do anything until Mixin updates ASM itself.

**Comment by Runemoro** [comment] 2019-01-01 19:30
> Sounds like Fabric should fix it in their fork, it doesn't make sense for Mixin to do anything until Mixin updates ASM itself.

This is a Mixin bug too. From the documentation of LocalVariableNode, the second parameter is "The type descriptor of this local variable." A class name without the `L...;` isn't a valid descriptor, even if ASM 6 doesn't throw an exception.

**Comment by asiekierka** [comment] 2019-01-02 05:30
@DemonWav I'm angry that this was reported on this tracker and not *our* tracker, FWIW.

I have already caught a few ASM-specific changes, but it's an ongoing process.

**Comment by asiekierka** [comment] 2019-01-02 07:00
I have evaluated all uses of ClassNode.name and found another seemingly incorrect class name->type conversion, fixed on our side in https://github.com/FabricMC/Mixin/commit/ad4385de6c10f3d5b2b955d137bfd284a772e565

**Comment by Mumfrey** [comment] 2019-01-02 11:33
Thanks @asiekierka I'll fold in those changes.

**Closed** 2019-09-16 15:15 UTC
Labels: core, enhancement
