### ISSUE TITLE
"No mixin host service is available" when loading production jar in FML

### ISSUE THREAD

**Issue by mrgrim** [SpongePowered/Mixin#278] opened 2018-08-06 23:38 UTC
I have a FML/Mixin based coremod I've been working on here: https://github.com/mrgrim/MUP

It works great in a dev environment, and it works fine in prod with Mixin 0.7.2 or older. However, anything newer than that, and all I get is this error. I'm attaching the debug log.

I've tried for hours to try to even vaguely understand this service thing and how it could possibly be failing, but I'm at the end of my rope. Any help you can provide would be greatly appreciated.

Thanks.

[debug.log](https://github.com/SpongePowered/Mixin/files/2264454/debug.log)

**Comment by Mumfrey** [comment] 2018-08-08 09:35
Most likely you've just not shadowed the contents of the Mixin jar properly. If you forget to shadow the `services` from `META-INF` then there won't be any service declarations in your output jar so Java service loader won't load the service host.

Closing this as it's not a bug but you can post additional messages below if needed.

**Closed by Mumfrey** 2018-08-08 09:35 UTC
Labels: question

**Comment by Mumfrey** [comment] 2018-08-08 09:50
I have cloned and built your project and as I suspected, your mod artefact is failing to include the `services` declarations from Mixin. Most likely [this line in your build.gradle](https://github.com/mrgrim/MUP/blob/master/build.gradle#L145) which is excluding `META-INF` entirely without subsequently merging the service files.

**Comment by mrgrim** [comment] 2018-08-09 00:11
Thank you! I added the following after the exclude:

```
        from(project.zipTree(dep)){
            include 'META-INF/services', 'META-INF/services/**'
        }
```

And it works perfectly! I figured I messed something up. :) Hopefully this is easy to find with Google for other folks in the future.

**Comment by Mumfrey** [comment] 2018-08-09 15:09
Likewise for anyone hitting this issue with Google and wanting further information about the Java service model for extensible applications:

* [Link to the Oracle Docs on Services](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html)

**Comment by Mumfrey** [comment] 2018-08-09 15:10
I should also point out that your method won't work if there are multiple jars containing services of the same type and that the Gradle Shadow plugin provides the `mergeServiceFiles` task for precisely this reason.
