### ISSUE TITLE
Interfaces are present and they aren't at the same time

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#62] opened 2015-08-15 14:32 UTC
I'm mixing into net.minecraft.block.material.MapColor to implement org.spongepowered.data.type.MapColor, and the exported decompile of the mixin code shows that the interface is present after the mixin is applied. However attempting to list the interfaces results in no output, just as it would without the mixin and when I attempt to cast to the MapColor interface in SpongeAPI it fails. I've checked my types and I'm using the correct type in the annotation and implements declaration.

Here's the Mixin

```java
package org.spongepowered.common.mixin.core.data.types;

import net.minecraft.block.material.MapColor;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.common.interfaces.data.IMixinMapColor;

@Mixin(MapColor.class)
public class MixinMapColor implements org.spongepowered.api.data.type.MapColor, IMixinMapColor {
    @Shadow public int colorValue;
    @Shadow public int colorIndex;

    private String name;

    @Override
    public int getIndex() {
        return this.colorIndex;
    }

    @Override
    public int getRGB() {
        return this.colorValue;
    }

    @Override
    public String getId() {
        return this.name;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }
}
```
Since the MapColor interface is a publicly known description of maps I'll post the merged class too

```java
package net.minecraft.block.material;

import org.spongepowered.asm.mixin.transformer.meta.MixinMerged;
import org.spongepowered.common.interfaces.data.IMixinMapColor;

public class MapColor implements org.spongepowered.api.data.type.MapColor, IMixinMapColor {
    public static final MapColor[] mapColorArray = new MapColor[64];
    public static final MapColor airColor = new MapColor(0, 0);
    public static final MapColor grassColor = new MapColor(1, 8368696);
    public static final MapColor sandColor = new MapColor(2, 16247203);
    public static final MapColor clothColor = new MapColor(3, 10987431);
    public static final MapColor tntColor = new MapColor(4, 16711680);
    public static final MapColor iceColor = new MapColor(5, 10526975);
    public static final MapColor ironColor = new MapColor(6, 10987431);
    public static final MapColor foliageColor = new MapColor(7, 31744);
    public static final MapColor snowColor = new MapColor(8, 16777215);
    public static final MapColor clayColor = new MapColor(9, 10791096);
    public static final MapColor dirtColor = new MapColor(10, 12020271);
    public static final MapColor stoneColor = new MapColor(11, 7368816);
    public static final MapColor waterColor = new MapColor(12, 4210943);
    public static final MapColor woodColor = new MapColor(13, 6837042);
    public static final MapColor quartzColor = new MapColor(14, 16776437);
    public static final MapColor adobeColor = new MapColor(15, 14188339);
    public static final MapColor magentaColor = new MapColor(16, 11685080);
    public static final MapColor lightBlueColor = new MapColor(17, 6724056);
    public static final MapColor yellowColor = new MapColor(18, 15066419);
    public static final MapColor limeColor = new MapColor(19, 8375321);
    public static final MapColor pinkColor = new MapColor(20, 15892389);
    public static final MapColor grayColor = new MapColor(21, 5000268);
    public static final MapColor silverColor = new MapColor(22, 10066329);
    public static final MapColor cyanColor = new MapColor(23, 5013401);
    public static final MapColor purpleColor = new MapColor(24, 8339378);
    public static final MapColor blueColor = new MapColor(25, 3361970);
    public static final MapColor brownColor = new MapColor(26, 6704179);
    public static final MapColor greenColor = new MapColor(27, 6717235);
    public static final MapColor redColor = new MapColor(28, 10040115);
    public static final MapColor blackColor = new MapColor(29, 1644825);
    public static final MapColor goldColor = new MapColor(30, 16445005);
    public static final MapColor diamondColor = new MapColor(31, 6085589);
    public static final MapColor lapisColor = new MapColor(32, 4882687);
    public static final MapColor emeraldColor = new MapColor(33, '\ud93a');
    public static final MapColor obsidianColor = new MapColor(34, 1381407);
    public static final MapColor netherrackColor = new MapColor(35, 7340544);
    public final int colorValue;
    public final int colorIndex;
    private static final String __OBFID = "CL_00000544";
    private String name;

    private MapColor(int index, int color) {
        if(index >= 0 && index <= 63) {
            this.colorIndex = index;
            this.colorValue = color;
            mapColorArray[index] = this;
        } else {
            throw new IndexOutOfBoundsException("Map colour ID must be between 0 and 63 (inclusive)");
        }
    }

    @MixinMerged(
        mixin = "org.spongepowered.common.mixin.core.data.types.MixinMapColor",
        priority = 1000,
        sessionId = "4f7f37d5-850a-4b5c-ac6c-dfdbf63c5169"
    )
    public int getIndex() {
        return this.colorIndex;
    }

    @MixinMerged(
        mixin = "org.spongepowered.common.mixin.core.data.types.MixinMapColor",
        priority = 1000,
        sessionId = "4f7f37d5-850a-4b5c-ac6c-dfdbf63c5169"
    )
    public int getRGB() {
        return this.colorValue;
    }

    @MixinMerged(
        mixin = "org.spongepowered.common.mixin.core.data.types.MixinMapColor",
        priority = 1000,
        sessionId = "4f7f37d5-850a-4b5c-ac6c-dfdbf63c5169"
    )
    public String getId() {
        return this.name;
    }

    @MixinMerged(
        mixin = "org.spongepowered.common.mixin.core.data.types.MixinMapColor",
        priority = 1000,
        sessionId = "4f7f37d5-850a-4b5c-ac6c-dfdbf63c5169"
    )
    public String getName() {
        return this.name;
    }

    @MixinMerged(
        mixin = "org.spongepowered.common.mixin.core.data.types.MixinMapColor",
        priority = 1000,
        sessionId = "4f7f37d5-850a-4b5c-ac6c-dfdbf63c5169"
    )
    public void setName(String name) {
        this.name = name;
    }
}
```

**Comment by gabizou** [comment] 2015-08-15 16:08
You need to mark the `getName()` as `@Intrinsic`

**Comment by modwizcode** [comment] 2015-08-15 17:57
Oh? Why does the output seem right then?

**Comment by modwizcode** [comment] 2015-08-15 20:37
Why? That doesn't make any sense. `net.minecraft.block.material.MapColor` doesn't contain a `getName()` method or any conflicting interfaces. I'm not even soft-implementing. So the description of `@Intrinsic` is unrelated or it covers more than it says.

**Comment by modwizcode** [comment] 2015-08-16 02:33
Update, seems the issue is related to reflection. Somehow reflective access to the static fields doesn't contain the same properties as direct access does. When I use the fields directly without trying to reflectively access them, everything works as intended.

**Comment by gabizou** [comment] 2015-08-16 18:16
Sorry, I misread the mixin as `getName()` wasn't being `@MixinMerged`, believing that the MapColor actually had extended `IWorldNameable`, which has happened in the past with a few mixins.

**Comment by Mumfrey** [comment] 2015-08-16 18:21
@modwizcode if you're experiencing issues with reflection vs. reality, make sure that you're reflecting in the correct classloader. As far as I can tell this isn't a bug, mixin applies much earlier than any reflection-related class metadata generation, so it's almost certain that if reflection says the interface "isn't there" then you're reflecting against something where the interface genuinely *isn't* there!

**Comment by Mumfrey** [comment] 2015-08-17 10:18
As far as I can tell, the listing in your original description actually just shows that this is working as intended, feel free to re-open if you can rule out the classloader issue but I'm closing this for now as I can't see an issue that needs to be fixed on Mixin's end at the moment.

**Closed by Mumfrey** 2015-08-17 10:18 UTC
