### ISSUE TITLE
Invalid Refmap generation for subclasses of obfuscated classes by AP

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#326] opened 2019-06-05 03:08 UTC
In writing [a mixin targeting a Forge added class extending a Minecraft class](https://gist.github.com/gabizou/2ba9a83798693c15d494d4580533133a#file-mixinblockfluidclassic-java-L60), the [`@Inject` target](https://gist.github.com/gabizou/2ba9a83798693c15d494d4580533133a#file-mixinblockfluidclassic-java-L68) gets a refmap pointing to [`net/minecraft/block/Block;updateTick()`](https://gist.github.com/gabizou/2ba9a83798693c15d494d4580533133a#file-mixin-forge-refmap-json-L4) which results in the error outlined [in the associated gist](https://gist.github.com/gabizou/2ba9a83798693c15d494d4580533133a#file-gistfile1-txt-L11).

From the production jar, it still looks like the target mixin is being remapped appropriately, as the method contents are being srg mapped, but from debugging the AP, I'm finding that the issue is within the generation as demonstrated by the screenshot below:

![Imgur](https://i.imgur.com/jE8WtrF.png)

I don't know if the ultimate resolution is to do an equality check on the mapping's owner and the method's owner, since in this case, we need to be getting the method's owner, not the mappings owner.

The workaround I [managed to dig up](https://github.com/SpongePowered/SpongeForge/commit/145b9d673d4499bab486c9399d2eb84ea59b7e33#diff-dac0e4d707e0f190f4046ba0123581fa) involved [using the extraSrgs argument](https://github.com/SpongePowered/SpongeForge/commit/0fb00f46f8af40790d7d9f23600e4000073a6886), though I think Mixins could emit a warning about the parent class being invalid in this case, not at production but at refmap creation time (though, again, because the refmap is being generated without the context of what is calling it, it's a little harder for this to work).

**Comment by Mumfrey** [comment] 2019-07-11 12:29
Yeah the entries in the method body being remapped correctly is expected, since their context is known. The whole reason that the AP has to generate the srgs at all is that the context of the mixin exists outside the scope of anything that's known to the compiler/obfuscator.

I can think of a couple of ways to fix this because the logic the AP uses for these kind of superclass resolutions has been corner-cased a couple of times in the past. The issue is basically that the binding in the mixin needs to be resolved in the same way a virtual call itself would be resolved, but the information to do that is scattered across several places at compile time.

I'll look into it and try and make the resolution a little smarter. Such a nice self-contained test case should make it easier to resolve a correct behaviour.

**Closed** 2019-09-16 15:15 UTC
Labels: accepted, annotation processor, bug
