### ISSUE TITLE
MemberInfo doesn't handle generic signatures

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#60] opened 2015-08-10 05:20 UTC
The annotation processor currently requires a generic signature to be present, in order to be able to find the target of an injection-related annotation. `compareElement`, called [here](https://github.com/SpongePowered/Mixin/blob/master/src/ap/java/org/spongepowered/tools/obfuscation/TypeHandle.java#L240), uses the generic signature of the `Element` being checked, requiring the `MemberInfo` to contain it as well.

However, `MemberInfo` doesn't correctly parse the generic singnature, resulting in Mixin failing to apply the mixin at runtime.

**Comment by Mumfrey** [comment] 2015-08-10 10:51
Hmm okay, the whole point of `rawSignature` was to deal with that but I guess it doesn't work if the element *has* a raw signature but it's not parsed correctly. I've literally just landed back in the UK following being away at gamescom so I'll take a look once my brain is back in gear later this week.

**Comment by Aaron1011** [comment] 2015-08-11 08:25
@Mumfrey: After looking at it more, I think the issue is that `findMethod` is doing things the opposite way it should - it searches for passed in signature with and without generics. However, unless you want to modify `MemberInfo` to correctly parse generics, it would be better to instead try stripping the generics out of each candidate signature.

**Comment by Mumfrey** [comment] 2015-08-11 10:20
I think that the reason the logic appears back to front is that the case it was designed to handle is when the mixin code *has* a generic type but the target type *doesn't* (which was the normal case with the MC classes). As I mentioned above I'll have a look at it once my brain has sufficiently recovered from last week.

**Comment by Mumfrey** [comment] 2015-11-24 23:10
Closing in favour of #66

**Closed by Mumfrey** 2015-11-24 23:10 UTC
Labels: bug
