### ISSUE TITLE
java.lang.NoSuchMethodException: org.spongepowered.asm.service.MixinService.getInstance()

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#210] opened 2017-09-26 13:15 UTC
Since I updated to 0.7.4, I get that error in the log.
java.lang.NoSuchMethodException: org.spongepowered.asm.service.MixinService.getInstance()
https://gist.github.com/Ordinastie/b2bd9fa7056ad3cabd242cfd2f2b1750#file-fml-log-L21

Doesn't seem to prevent any mixin to work though.

**Comment by Mumfrey** [comment] 2017-09-26 14:32
Ah, yes that's a refactoring fail right there. It doesn't matter too much if there is more than one service which is why that's not fatal, but what it does mean is that in production re-entrance wouldn't necessarily be detected because different parts of the subsystem might be using different services.

Should be simple to fix by fixing the reflective call to use the right name.

**Comment by Mumfrey** [comment] 2017-09-26 14:41
That should have fixed it, let me know if the problem persists. If the issue is resolved feel free to close this ticket.

**Comment by Mumfrey** [comment] 2017-09-27 12:28
It seems like there's some failure of classloader isolation going on, since fixing this issue leads to a LinkageError so I suspect I need to split the service down into parts which can be more effectively isolated before this is going to be resolved.

The whole purpose of isolating support for LaunchWrapper into a service is to support the java 9 branch and switching to modlauncher, but at the moment there's a chicken/egg situation where the service itself needs classloader isolation but is unable to isolate itself. 🙁 

I'm either going to split the service into a boot service and runtime service, or just have the outer service bootstrap its own inner implementation beause at the moment there's no elegant way to make it work as-is without moving the re-entrance lock out of the service, which causes some other issues which would be ugly to fix.

In order to resolve this issue **for now** I am going to re-enable the dependency on launchwrapper so that I can add the classloader exclusion before boot, and then spend some time fixing the issue properly ready for merging the java 9 functionality when it's ready.

I'm going to close this issue because the original problem above should now be resolved, and consider the isolation issue a separate problem that I need to solve.

**Closed** 2017-09-27 15:26 UTC
Labels: acceptance testing, accepted, bug, core

**Comment by Mumfrey** [comment] 2017-10-10 21:00
This should now be fully resolved by the addition of the bootstrap services.
